version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run: "npm i"
      - run: "npm run lint"

  test:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run: "npm i"
      - run: "npm run test"
 
  analyse:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run: "npm audit"

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
